name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `master` branch
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Install, build, and upload your site
        uses: actions/setup-node@v3
        with:
          # path: . # The root location of your Astro project inside the repository. (optional)
          node-version: 22.12.0 # The specific version of Node that should be used to build your site. Defaults to 18. (optional)
          package-manager: pnpm # The Node package manager that should be used to install dependencies and build your site. Automatically detected based on your lockfile. (optional)
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies using pnpm
        run: pnpm install  # This step installs your dependencies
      - name: Build the site using Astro
        run: pnpm run build  # This will build the Astro project
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download the artifact
        uses: actions/download-artifact@v3
        with:
          name: https://anaadeladelrosario.github.io  # The name of the artifact uploaded in the build step
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          # Optional: specify the directory if needed, default is `./dist`
          publish_dir: ./dist  # Ensure this matches your Astro build output folder